### ISSUE TITLE
Including cljs-pdfkit can break existing tests

### ISSUE THREAD

**Issue by wontheone1** [whamtet/cljs-pdfkit#2]
After including this in dependencies, tests are broken. 

either this
```
Caused by: clojure.lang.ExceptionInfo: Referred var cljs.test/is does not exist {:tag :cljs/analysis-error}
```
or complain about cljs.test/testing does not exist.
but we noticed that it is using older versions of clojure script when building
`Building ...
Reading analysis cache for jar:file:/Users/wseobseo/.m2/repository/org/clojure/clojurescript/1.7.170/clojurescript-1.7.170-aot.jar!/cljs/core.cljs`
So including dependencies as 
`[cljs-pdfkit "0.1.0-SNAPSHOT" :exclusions [[org.clojure/clojurescript]]]`
fixed the tests again.
I think this can be mentioned in README so that they don't download and use older(or newer) cljs than they use normally for the project.

**Comment by whamtet** [comment]
Thanks for noticing this won, I'll look into it this weekend.

Matthew

**Comment by whamtet** [comment]
@wontheone1 I've fixed this by making clojurescript a dependency in the `:repl` profile so that it is no longer transitively included

**Comment by wontheone1** [comment]
👍  great!
