### ISSUE TITLE
Releasing immutable versions

### ISSUE THREAD

**Issue by wontheone1** [whamtet/cljs-pdfkit#3]
Hello,
Correct me if I am wrong.
Currently this library has only snapshot versions released, the problem is as the snapshot version is mutable, it's not safe to include in production services or anything serious. Does the library author @whamtet have a plan/time to release immutable version? (It can be a beta release too.)

Please let me know what you think.

Thanks!

**Comment by whamtet** [comment]
Yes,

I'll update the versions shortly.

Matt

**Comment by wontheone1** [comment]
@whamtet  :) Hi , I don't mean to give pressure or anything but do you know when it will be released?

**Comment by whamtet** [comment]
How about this weekend?

**Comment by wontheone1** [comment]
@whamtet sounds good :) Just wanted to check the timeline. Thanks

**Comment by whamtet** [comment]
Cool

**Comment by wontheone1** [comment]
@whamtet Hi, Regarding this issue, I just wanted to mention, all dependencies of the library should also be immutable versions. There is one snapshot version among the dependency
`[redlobster "0.2.2-SNAPSHOT"]`
https://github.com/whamtet/cljs-pdfkit/blob/master/project.clj#L8
thanks!

**Comment by whamtet** [comment]
Yes

**Comment by whamtet** [comment]
Fixed in latest release.  Also pushed versions to clojars.

**Comment by wontheone1** [comment]
thanks
